package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.GradleBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'StockSimulatorDeploy'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("StockSimulatorDeploy")) {
    params {
        expect {
            password("env.DOCKER_PASSWORD", "zxx775d03cbe80d301b", label = "Docker Registry Password", display = ParameterDisplay.HIDDEN)
        }
        update {
            password("env.DOCKER_PASSWORD", "zxxf4d764c104bd5c231db1675f6ac32a92fb67040debd0eda21daa394c6c1e5e51287c897735de911c775d03cbe80d301b", label = "Docker Registry Password", display = ParameterDisplay.HIDDEN)
        }
        expect {
            password("env.DOCKER_USER", "zxx775d03cbe80d301b", label = "Docker Registry User", display = ParameterDisplay.HIDDEN)
        }
        update {
            password("env.DOCKER_USER", "zxx6e32f17b12479f7b86d484196ab72657", label = "Docker Registry User", display = ParameterDisplay.HIDDEN)
        }
    }

    expectSteps {
        gradle {
            name = "Gradle Build"
            tasks = "build -x test --parallel"
            useGradleWrapper = true
        }
        script {
            name = "Docker Login"
            scriptContent = "echo %env.DOCKER_PASSWORD% | docker login ghcr.io -u %env.DOCKER_USER% --password-stdin"
        }
        script {
            name = "Build & Push Backend Images"
            scriptContent = """
                #!/bin/bash
                set -e
                
                REGISTRY="ghcr.io"
                IMAGE_PREFIX="park-gijun/stocksim"
                
                SERVICES="eureka-server api-gateway user-service stock-service trading-service event-service scheduler-service news-service"
                
                for SERVICE in ${'$'}SERVICES; do
                    echo "Building ${'$'}SERVICE..."
                    cd backend/${'$'}SERVICE
                    docker build -t ${'$'}REGISTRY/${'$'}IMAGE_PREFIX/${'$'}SERVICE:latest .
                    docker push ${'$'}REGISTRY/${'$'}IMAGE_PREFIX/${'$'}SERVICE:latest
                    cd ../..
                    echo "${'$'}SERVICE done."
                done
                
                echo "All backend images built and pushed."
            """.trimIndent()
        }
        script {
            name = "Build & Push Frontend Image"
            scriptContent = """
                #!/bin/bash
                set -e
                
                echo "Building Frontend..."
                cd frontend
                docker build -t ghcr.io/park-gijun/stocksim/frontend:latest .
                docker push ghcr.io/park-gijun/stocksim/frontend:latest
                cd ..
                
                echo "Frontend image built and pushed."
            """.trimIndent()
        }
        script {
            name = "Deploy"
            scriptContent = """
                #!/bin/bash
                set -e
                
                # Copy infrastructure configuration files to /deploy
                echo "Copying infrastructure and config files..."
                cp -rf docker-compose.yml /deploy/
                cp -rf infra /deploy/
                
                cd /deploy
                
                # Login to registry
                echo %env.DOCKER_PASSWORD% | docker login ghcr.io -u %env.DOCKER_USER% --password-stdin
                
                # Pull new images
                docker-compose -p stock-simulator --profile all pull --ignore-pull-failures
                
                echo "Full deployment..."
                
                # 1. Eureka first
                docker-compose -p stock-simulator --profile all up -d --no-deps --force-recreate eureka-server
                echo "Waiting for Eureka to start..."
                for i in ${'$'}(seq 1 12); do
                    if curl -sf http://stockSimulator-eureka-server:8761/actuator/health > /dev/null 2>&1; then
                        echo "Eureka is ready!"
                        break
                    fi
                    echo "  Attempt ${'$'}i/12 - Eureka not ready yet, waiting 10s..."
                    sleep 10
                done
                
                # 2. Backend services
                docker-compose -p stock-simulator --profile all up -d --no-deps --force-recreate user-service stock-service trading-service event-service scheduler-service news-service
                sleep 15
                
                # 3. API Gateway
                docker-compose -p stock-simulator --profile all up -d --no-deps --force-recreate api-gateway
                sleep 10
                
                # 4. Frontend
                docker-compose -p stock-simulator --profile all up -d --no-deps --force-recreate frontend
                
                echo "Deployment complete"
            """.trimIndent()
        }
        script {
            name = "Health Check"
            scriptContent = """
                #!/bin/bash
                set -e
                
                echo "Waiting for services to stabilize..."
                sleep 15
                
                # Check Eureka
                for i in ${'$'}(seq 1 6); do
                    if curl -sf http://stockSimulator-eureka-server:8761/actuator/health > /dev/null 2>&1; then
                        echo "Eureka is healthy"
                        break
                    fi
                    if [ "${'$'}i" = "6" ]; then
                        echo "Eureka health check failed"
                        exit 1
                    fi
                    echo "  Eureka attempt ${'$'}i/6 - waiting 10s..."
                    sleep 10
                done
                
                # Check API Gateway
                for i in ${'$'}(seq 1 6); do
                    if curl -sf http://stockSimulator-api-gateway:8080/actuator/health > /dev/null 2>&1; then
                        echo "API Gateway is healthy"
                        break
                    fi
                    if [ "${'$'}i" = "6" ]; then
                        echo "API Gateway health check failed"
                        exit 1
                    fi
                    echo "  Gateway attempt ${'$'}i/6 - waiting 10s..."
                    sleep 10
                done
                
                echo "All health checks passed!"
            """.trimIndent()
        }
    }
    steps {
        update<GradleBuildStep>(0) {
            clearConditions()
            tasks = "clean build -x test --parallel"
            param("teamcity.kubernetes.executor.pull.policy", "")
        }
        update<ScriptBuildStep>(1) {
            name = "Build & Push Backend Images"
            clearConditions()
            scriptContent = """
                #!/bin/bash
                  set -e
                
                  IMAGE_PREFIX="stocksim"
                
                  for SERVICE in eureka-server api-gateway user-service stock-service trading-service event-service scheduler-service news-service; do
                      echo "Building ${'$'}SERVICE..."
                      cd backend/${'$'}SERVICE
                      docker build --no-cache -t ${'$'}IMAGE_PREFIX/${'$'}SERVICE:latest .
                      cd ../..
                      echo "${'$'}SERVICE done."
                  done
                
                  echo "All backend images built."
                
                  4. "Build & Push Frontend Image" 스텝 → 스크립트를 이걸로 교체:
                
                  #!/bin/bash
                  set -e
                
                  echo "Building Frontend..."
                  cd frontend
                  docker build --no-cache -t stocksim/frontend:latest .
                  cd ..
                
                  echo "Frontend image built."
            """.trimIndent()
            param("teamcity.kubernetes.executor.pull.policy", "")
        }
        items.removeAt(2)
        update<ScriptBuildStep>(3) {
            clearConditions()
            scriptContent = """
                #!/bin/bash
                set -e
                
                # Copy infrastructure configuration files to /deploy
                echo "Copying infrastructure and config files..."
                cp -rf docker-compose.yml /deploy/
                cp -rf infra /deploy/
                
                cd /deploy
                
                # Login to registry
                echo %env.DOCKER_PASSWORD% | docker login ghcr.io -u %env.DOCKER_USER% --password-stdin
                
                # Pull new images
                docker compose -p stock-simulator --profile all pull --ignore-pull-failures
                
                echo "Full deployment..."
                
                # 1. Eureka first
                docker compose -p stock-simulator --profile all up -d --no-deps --force-recreate eureka-server
                echo "Waiting for Eureka to start..."
                for i in ${'$'}(seq 1 12); do
                    if curl -sf http://stockSimulator-eureka-server:8761/actuator/health > /dev/null 2>&1; then
                        echo "Eureka is ready!"
                        break
                    fi
                    echo "  Attempt ${'$'}i/12 - Eureka not ready yet, waiting 10s..."
                    sleep 10
                done
                
                # 2. Backend services
                docker compose -p stock-simulator --profile all up -d --no-deps --force-recreate user-service stock-service trading-service event-service scheduler-service news-service
                sleep 15
                
                # 3. API Gateway
                docker compose -p stock-simulator --profile all up -d --no-deps --force-recreate api-gateway
                sleep 10
                
                # 4. Frontend
                docker compose -p stock-simulator --profile all up -d --no-deps --force-recreate frontend
                
                echo "Deployment complete"
            """.trimIndent()
            param("teamcity.kubernetes.executor.pull.policy", "")
        }
    }
}
