package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'StockSimulatorDeploy'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("StockSimulatorDeploy")) {
    params {
        expect {
            password("env.DOCKER_USER", "zxx775d03cbe80d301b", label = "Docker Registry User", display = ParameterDisplay.HIDDEN)
        }
        update {
            password("env.DOCKER_USER", "zxx6e32f17b12479f7b86d484196ab72657", label = "Docker Registry User", display = ParameterDisplay.HIDDEN)
        }
    }
}
